#create database DATA225_DWH

#CREATING  CUSTOMER DIMENSION TABLE
CREATE TABLE DATA225_DWH.DIM_CUSTOMER
(
CUSTOMER_KEY INTEGER NOT NULL AUTO_INCREMENT ,
CUSTOMER_ID varchar (15),
GENDER      varchar (2),
RELATIONSHIP_START_DATE Date, 
CUSTOMER_AGE INTEGER,
SSN          varchar (15),
FIRST_NAME   varchar (50),
MIDDLE_NAME  varchar (50),
LAST_NAME    varchar (50),
PRIMARY_PHONE  varchar (50),
PRIMARY_EMAIL  varchar (100),
CURRENT_FLG    varchar(3),
BEGIN_EFF_DATE date,
END_EFF_DATE  date,
CHECKSUM_NUM      varchar(100),
PRIMARY KEY (CUSTOMER_KEY)
);

# CREATING ACCOUNT DIMESNSION TABLE
CREATE TABLE DATA225_DWH.DIM_ACCOUNT
(
ACCOUNT_KEY INTEGER NOT NULL AUTO_INCREMENT ,
ACCOUNT_ID varchar (15),
LOAN_ID varchar (15),
ACCOUNT_OPEN_DATE Date, 
FREQUENCY VARCHAR(50),
ACCOUNT_TYPE   VARCHAR(10),
ACCOUNT_STATUS VARCHAR(10),
ACCOUNT_PURPOSE VARCHAR(50),
ACCOUNT_LOCATION VARCHAR(20),
CURRENT_FLG    varchar(3),
BEGIN_EFF_DATE date,
END_EFF_DATE  date,
CHECKSUM_NUM      varchar(100),
PRIMARY KEY (ACCOUNT_KEY)
)
;
# CREATE FACTLESS FACT - ASSOCIATIVE ENTITY BETWEEN CUSTOMER AND ACCOUNT
CREATE TABLE DATA225_DWH.CUSTOMER_RLTD_ACCOUNT
(
CUST_ACCT_KEY INTEGER NOT NULL AUTO_INCREMENT ,
CUSTOMER_KEY INTEGER,
ACCOUNT_KEY  INTEGER,
ROLE_TYPE varchar(20),
CURRENT_FLG    varchar(3),
BEGIN_EFF_DATE date,
END_EFF_DATE  date,
CHECKSUM_NUM      varchar(100),
PRIMARY KEY (CUST_ACCT_KEY),
FOREIGN KEY (ACCOUNT_KEY) REFERENCES DATA225_DWH.DIM_ACCOUNT(ACCOUNT_KEY),
FOREIGN KEY (CUSTOMER_KEY) REFERENCES DATA225_DWH.DIM_CUSTOMER(CUSTOMER_KEY)
)
;

CREATE TABLE DATA225_DWH.DIM_TIME
(
    DIM_TIME_KEY INTEGER NOT NULL AUTO_INCREMENT ,
    PERIOD_TYPE VARCHAR(2),
    HOLIDAY_FLAG VARCHAR(2),
    DAY_NAME VARCHAR(15),
    RUN_DATE    DATE,
    RUN_YEAR   INTEGER,
    RUN_MONTH  INTEGER,
    RUN_DAY    INTEGER,
    RUN_QUARTER VARCHAR(3),
    WEEK        VARCHAR(15),
    WEEKDAY VARCHAR(15),
    MONTH_AND_YEAR VARCHAR(15),
    TIMEZONE_ID VARCHAR(15),
    TIMEZONE VARCHAR(15),
    TIMEZONE_OFFSET VARCHAR(15),
    PRIMARY KEY (DIM_TIME_KEY)
    )
    ;
CREATE TABLE DATA225_DWH.FACT_TRANSACTION_DETAIL
(
TRANSACTION_DETAIL_KEY INTEGER NOT NULL AUTO_INCREMENT ,
DIM_TIME_KEY INTEGER,
TRAN_SERIAL_NUM VARCHAR(15),
TRANS_ID VARCHAR(15),
ACCOUNT_KEY INTEGER,
TRANS_Type VARCHAR(10),
TRAN_AMOUNT  DECIMAL(12,4),
ACC_RUNNING_BALANCE DECIMAL(12,4),
TRANS_DATE  DATE,
TRANS_TIME VARCHAR(16),
FRAUD_FLAG VARCHAR(3),
TRAN_CAT VARCHAR(20),
TIME_ZONEID VARCHAR(20),
PRIMARY KEY (TRANSACTION_DETAIL_KEY),
FOREIGN KEY (ACCOUNT_KEY) REFERENCES DATA225_DWH.DIM_ACCOUNT(ACCOUNT_KEY),
FOREIGN KEY (DIM_TIME_KEY) REFERENCES DATA225_DWH.DIM_TIME(DIM_TIME_KEY)
)
    




